workflows:
  widgetbook-base:
    name: Widgetbook Workflow Base
    working_directory: app_widgetbook
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'staging'
          include: true
    environment:
      # Used so the $WIDGETBOOK_API_KEY is accessible as it's part of the
      # "Widgetbook Credentials" group
      groups:
        - Widgetbook Credentials
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Get dependencies
        script: flutter pub get

      - name: Run build runner
        script: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Website
        script: flutter build web -t lib/app.widgetbook.dart

      - name: Install Widgetbook CLI
        script: dart pub global activate widgetbook_cli 3.0.0-beta.22

      - name: Upload Widgetbook
        script: |
          widgetbook publish \
                --api-key $WIDGETBOOK_API_KEY \
                --branch $CM_BRANCH
  widgetbook-head:
    name: Widgetbook Workflow Head
    working_directory: app_widgetbook
    triggering:
      events:
        - pull_request
    environment:
      # Used so the $WIDGETBOOK_API_KEY is accessible as it's part of the
      # "Widgetbook Credentials" group
      groups:
        - Widgetbook Credentials
    
    scripts:
      - name: Switch branch
        script: |
          git switch -c $CM_BRANCH
      - name: Get Flutter packages
        script: | 
          echo "LOG"
          git log
          echo "HEAD SHA"
          git rev-parse HEAD
          echo "Staging SHA"
          git rev-parse $CM_PULL_REQUEST_DEST
          echo "Commit"
          echo $CM_COMMIT
          echo "Branches"
          git branch
          echo "Remote Branches"
          git branch -r
          echo "Diff"
          git diff $CM_PULL_REQUEST_DEST
      - name: Get Flutter packages
        script: | 
          echo "Get"
          flutter packages pub get
      - name: Get dependencies
        script: flutter pub get

      - name: Run build runner
        script: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Website
        script: flutter build web -t lib/app.widgetbook.dart

      - name: Install Widgetbook CLI
        script: dart pub global activate widgetbook_cli 3.0.0-beta.22

      - name: Upload Widgetbook
        script: |
          echo $CM_PULL_REQUEST_DEST
          widgetbook publish \
                --api-key $WIDGETBOOK_API_KEY \
                --branch $CM_BRANCH \
                --base-branch $CM_PULL_REQUEST_DEST