trigger:
  branches:
    include:
    - '*'

stages:
- stage: WidgetbookHostingStage
  dependsOn: []
  displayName: Hosting
  jobs:

  - job: HostingJob
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Hosting
    steps:

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: Bash@3
      displayName: "Run build_runner"
      inputs:
        targetType: 'inline'
        workingDirectory: 'app_widgetbook'
        script: |
          $(FlutterToolPath)/flutter pub get 
          $(FlutterToolPath)/flutter pub run build_runner build --delete-conflicting-outputs

    - task: Bash@3
      displayName: "Build Widgetbook"
      inputs:
        targetType: 'inline'
        workingDirectory: 'app_widgetbook'
        script: |
          $(FlutterToolPath)/flutter build web -t lib/app.widgetbook.dart

    - task: Bash@3
      displayName: "Activate Widgetbook CLI"
      inputs:
        targetType: 'inline'
        script: |
          $(FlutterToolPath)/flutter pub global activate widgetbook_cli 3.0.0-beta.11

    - task: Bash@3
      displayName: "Upload Widgetbook"
      inputs:
        targetType: 'inline'
        workingDirectory: 'app_widgetbook'
        script: |
          export PATH="/bin/:/usr/bin:$(FlutterToolPath):$(FlutterPubCachePath)"
          widgetbook publish \
              --api-key gw1v77QLlYFlf10GsfmuOPf2D8MUk7c5 \
              --branch '$(Build.SourceBranch)' \
              --repository '$(Build.DefinitionName)' \
              --commit '$(Build.SourceVersion)' \
              --actor '$(Build.SourceVersionAuthor)' \
              --base-branch '$(System.PullRequest.TargetBranch)' \
              --git-provider Azure