/// Flutter icons TwitterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class TwitterIcons {
  TwitterIcons._();

  static const _kFontFam = 'TwitterIcons';
  static const String? _kFontPkg = 'core';

  static const IconData user = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData search_fill = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData search = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData share = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData topics = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData user_fill = IconData(
    0xe823,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData add_feather_fill = IconData(
    0xe900,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData apple = IconData(
    0xe901,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData back = IconData(
    0xe902,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bell_fill = IconData(
    0xe903,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bell = IconData(
    0xe904,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bookmark = IconData(
    0xe905,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bulb = IconData(
    0xe906,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData calendar = IconData(
    0xe907,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData close = IconData(
    0xe908,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData down = IconData(
    0xe909,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eye_crossed = IconData(
    0xe90a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eye = IconData(
    0xe90b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData feature = IconData(
    0xe90c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData gif = IconData(
    0xe90d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData google = IconData(
    0xe90e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData hash = IconData(
    0xe90f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData heart_fill = IconData(
    0xe910,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData heart = IconData(
    0xe911,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData home_fill = IconData(
    0xe912,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData home = IconData(
    0xe913,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData image = IconData(
    0xe914,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData info = IconData(
    0xe915,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData link = IconData(
    0xe916,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData list = IconData(
    0xe917,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mail_fill = IconData(
    0xe918,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mail = IconData(
    0xe919,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData map_pin = IconData(
    0xe91a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData more = IconData(
    0xe91b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pin = IconData(
    0xe91c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData plus = IconData(
    0xe91d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData poll = IconData(
    0xe91e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData qr = IconData(
    0xe91f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData reply_fill = IconData(
    0xe920,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData reply = IconData(
    0xe921,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData retweet = IconData(
    0xe922,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
