name: Upload review
on:
  pull_request:
    branches:
      - staging
jobs:
  build:
    defaults:
      run:
        working-directory: ./app_widgetbook

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: diff
        run: | 
          echo $GITHUB_BASE_REF
          git branch -a
          git diff origin/$GITHUB_BASE_REF

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 

      - name: Get dependencies
        run: flutter pub get

      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Website
        run: flutter build web -t lib/app.widgetbook.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli 3.0.0-beta.23

      - name: Upload Widgetbook
        run: |
          widgetbook publish \
                --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }} \
                --repository \
                $GITHUB_REPOSITORY \
                --actor \
                $GITHUB_ACTOR \
                --base-branch \
                $GITHUB_BASE_REF \
                --pr ${{ github.event.number }} \
                --github-token ${{ secrets.GITHUB_TOKEN }}
